In [1]:
import numpy as np
import pandas as pd

#load the dataset
file_path = 'advertising.csv'
df = pd.read_csv(file_path )
df

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0
...,...,...,...,...,...,...,...,...,...,...
995,62.24,55,26386.56,249.15,Optimized content strategy,South Manuel,0,Canada,05-09-2016 18:00,0
996,49.46,31,54899.83,261.55,Optimized content strategy,Davidton,1,Italy,06-09-2016 00:00,1
997,52.12,48,25621.46,136.30,Organic bottom-line service-desk,Davidton,0,Canada,06-09-2016 06:00,0
998,68.85,19,38609.61,277.05,Optimized content strategy,West Terrifurt,0,San Marino,06-09-2016 12:00,0
999,55.58,47,74547.86,294.08,Monitored national standardization,Davidton,0,Nauru,06-09-2016 18:00,1

In [2]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0

In [3]:
df.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='object')

In [4]:
df.isnull()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [5]:
from sklearn.model_selection import train_test_split

#select feautures(exclude non-numeric / ID-Like colums)
X = df[['Daily Time Spent on Site', 'Age', 'Area Income', 'Daily Internet Usage', 'Male']]
        

#Target variable
y = df['Clicked on Ad']

#split the data (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# shape of the splits
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
#=======================================================================================================================================
# stratified sampling -cross validation
#=======================================================================================================================================
# Initialize and fit the logistic regression model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
# prompt: calculate the training and test accuracy
# make predictions on the training and test sets 
y_train_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)
# calculate accuracy scores
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
# print the accuracy scores
print(f"Training Accuracy: {train_accuracy}")
print(f"Test Accuracy: {test_accuracy}")

Training Accuracy: 0.5214285714285715
Test Accuracy: 0.49333333333333335

In [7]:
# K-Fold cross validation
#================================================================================================================

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')

#set up shufflesplit cross-validator
from sklearn.model_selection import KFold, cross_validate
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

from sklearn.model_selection import ShuffleSplit, cross_validate
shuffle_split = ShuffleSplit(n_splits=200, test_size=0.3, random_state=42)


#perform cross-validation and collect both train and test scores
cv_result = cross_validate(model, X, y, cv=shuffle_split, scoring='accuracy', return_train_score=True)

#Extract train and test scores
train_scores = cv_result['train_score']
test_scores = cv_result['test_score']

#show individual scores and their means
print("cross validation: train accuracy:" , np.round(train_scores.mean(),2))
print("cross validation: test accuracy:" , np.round(test_scores.mean(),2))

cross validation: train accuracy: 0.54
cross validation: test accuracy: 0.51